"use client"

import { useState, useEffect } from "react"
import { Heart, ShoppingCart } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useCart } from "@/hooks/use-cart"
import { toast } from "@/hooks/use-toast"

const products = [
  // SMARTPHONES - 25 produtos
  {
    id: 31,
    name: "iPhone 15 Pro Max 256GB Titânio Natural",
    price: 8999.9,
    installments: "12x sem juros de R$ 749,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Apple",
  },
  {
    id: 32,
    name: "iPhone 15 Pro 128GB Azul Titânio",
    price: 7999.9,
    installments: "12x sem juros de R$ 666,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Apple",
  },
  {
    id: 33,
    name: "iPhone 15 128GB Rosa",
    price: 6299.9,
    installments: "12x sem juros de R$ 524,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Apple",
  },
  {
    id: 34,
    name: "iPhone 14 Pro Max 256GB Roxo Profundo",
    price: 7499.9,
    installments: "12x sem juros de R$ 624,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Apple",
  },
  {
    id: 35,
    name: "iPhone 14 128GB Azul",
    price: 4999.9,
    installments: "12x sem juros de R$ 416,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Apple",
  },
  {
    id: 36,
    name: "iPhone 13 128GB Meia-noite",
    price: 3999.9,
    installments: "12x sem juros de R$ 333,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Apple",
  },
  {
    id: 37,
    name: "Samsung Galaxy S24 Ultra 512GB Preto",
    price: 7299.9,
    installments: "12x sem juros de R$ 608,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Samsung",
  },
  {
    id: 38,
    name: "Samsung Galaxy S24+ 256GB Violeta",
    price: 5999.9,
    installments: "12x sem juros de R$ 499,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Samsung",
  },
  {
    id: 39,
    name: "Samsung Galaxy S24 256GB Amarelo",
    price: 4999.9,
    installments: "12x sem juros de R$ 416,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Samsung",
  },
  {
    id: 40,
    name: "Samsung Galaxy S23 FE 256GB Grafite",
    price: 2999.9,
    installments: "12x sem juros de R$ 249,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Samsung",
  },
  {
    id: 41,
    name: "Samsung Galaxy A54 5G 256GB Violeta",
    price: 1899.9,
    installments: "12x sem juros de R$ 158,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Samsung",
  },
  {
    id: 42,
    name: "Samsung Galaxy A34 5G 128GB Prata",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Samsung",
  },
  {
    id: 43,
    name: "Samsung Galaxy A24 128GB Preto",
    price: 999.9,
    installments: "12x sem juros de R$ 83,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Samsung",
  },
  {
    id: 44,
    name: "Xiaomi Redmi Note 13 Pro+ 5G 256GB Azul",
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Xiaomi",
  },
  {
    id: 45,
    name: "Xiaomi Redmi Note 13 Pro 256GB Roxo",
    price: 1299.9,
    installments: "12x sem juros de R$ 108,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Xiaomi",
  },
  {
    id: 46,
    name: "Xiaomi Redmi Note 13 128GB Verde",
    price: 899.9,
    installments: "12x sem juros de R$ 74,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Xiaomi",
  },
  {
    id: 47,
    name: "Xiaomi POCO X6 Pro 5G 256GB Amarelo",
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Xiaomi",
  },
  {
    id: 48,
    name: "Motorola Edge 40 Neo 256GB Preto",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Motorola",
  },
  {
    id: 49,
    name: "Motorola Moto G84 5G 256GB Azul",
    price: 1199.9,
    installments: "12x sem juros de R$ 99,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Motorola",
  },
  {
    id: 50,
    name: "Motorola Moto G54 5G 256GB Violeta",
    price: 899.9,
    installments: "12x sem juros de R$ 74,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Motorola",
  },
  {
    id: 51,
    name: "OnePlus 12 5G 256GB Verde",
    price: 4299.9,
    installments: "12x sem juros de R$ 358,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "OnePlus",
  },
  {
    id: 52,
    name: "OnePlus 11 5G 256GB Preto",
    price: 3299.9,
    installments: "12x sem juros de R$ 274,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "OnePlus",
  },
  {
    id: 53,
    name: "Google Pixel 8 Pro 256GB Obsidian",
    price: 5999.9,
    installments: "12x sem juros de R$ 499,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Google",
  },
  {
    id: 54,
    name: "Google Pixel 8 128GB Bay",
    price: 3999.9,
    installments: "12x sem juros de R$ 333,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Google",
  },
  {
    id: 55,
    name: "Realme GT Neo 5 256GB Azul",
    price: 1899.9,
    installments: "12x sem juros de R$ 158,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    brand: "Realme",
  },

  // GELADEIRAS - 25 produtos
  {
    id: 1,
    name: "Geladeira Brastemp Frost Free Duplex 400L Branca BRM54HB",
    price: 2299.9,
    installments: "12x sem juros de R$ 191,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Brastemp",
  },
  {
    id: 2,
    name: "Refrigerador Electrolux Duplex 380L Inox DFN41",
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Electrolux",
  },
  {
    id: 3,
    name: "Geladeira Samsung French Door 540L Prata RF23R62E3SR",
    price: 4299.9,
    installments: "12x sem juros de R$ 358,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Samsung",
  },
  {
    id: 56,
    name: "Geladeira Brastemp Side Inverse 540L Inox BRO80AE",
    price: 3799.9,
    installments: "12x sem juros de R$ 316,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Brastemp",
  },
  {
    id: 57,
    name: "Refrigerador Electrolux French Door 579L Inox DM84X",
    price: 4999.9,
    installments: "12x sem juros de R$ 416,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Electrolux",
  },
  {
    id: 58,
    name: "Geladeira Samsung Duplex 453L Branca RT46K6241WW",
    price: 2599.9,
    installments: "12x sem juros de R$ 216,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Samsung",
  },
  {
    id: 59,
    name: "Geladeira LG French Door 530L Inox GC-L197CSSL",
    price: 3999.9,
    installments: "12x sem juros de R$ 333,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "LG",
  },
  {
    id: 60,
    name: "Refrigerador Consul Duplex 340L Branca CRM39AB",
    price: 1699.9,
    installments: "12x sem juros de R$ 141,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Consul",
  },
  {
    id: 61,
    name: "Geladeira Brastemp Ative! 403L Branca BRM45HB",
    price: 2199.9,
    installments: "12x sem juros de R$ 183,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Brastemp",
  },
  {
    id: 62,
    name: "Refrigerador Electrolux Top Freezer 240L Branco RE31",
    price: 1299.9,
    installments: "12x sem juros de R$ 108,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Electrolux",
  },
  {
    id: 63,
    name: "Geladeira Samsung Side by Side 617L Inox RS62R5011M9",
    price: 5299.9,
    installments: "12x sem juros de R$ 441,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Samsung",
  },
  {
    id: 64,
    name: "Refrigerador LG Duplex 423L Prata GC-B419SLQL",
    price: 2799.9,
    installments: "12x sem juros de R$ 233,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "LG",
  },
  {
    id: 65,
    name: "Geladeira Consul Bem Estar 405L Branca CRM51AB",
    price: 2099.9,
    installments: "12x sem juros de R$ 174,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Consul",
  },
  {
    id: 66,
    name: "Refrigerador Brastemp Clean 378L Inox BRM42EK",
    price: 2399.9,
    installments: "12x sem juros de R$ 199,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Brastemp",
  },
  {
    id: 67,
    name: "Geladeira Electrolux Infinity 553L Inox DF82X",
    price: 4599.9,
    installments: "12x sem juros de R$ 383,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Electrolux",
  },
  {
    id: 68,
    name: "Refrigerador Samsung Twin Cooling Plus 384L RT38K50AJ",
    price: 2899.9,
    installments: "12x sem juros de R$ 241,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Samsung",
  },
  {
    id: 69,
    name: "Geladeira LG Door-in-Door 416L Inox GC-X247CQAV",
    price: 3599.9,
    installments: "12x sem juros de R$ 299,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "LG",
  },
  {
    id: 70,
    name: "Refrigerador Consul Facilite 300L Branca CRD37EB",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Consul",
  },
  {
    id: 71,
    name: "Geladeira Brastemp Gourmand 540L Inox BRO80AK",
    price: 4199.9,
    installments: "12x sem juros de R$ 349,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Brastemp",
  },
  {
    id: 72,
    name: "Refrigerador Electrolux Bottom Freezer 454L Inox IB53X",
    price: 3299.9,
    installments: "12x sem juros de R$ 274,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Electrolux",
  },
  {
    id: 73,
    name: "Geladeira Samsung Family Hub 614L Inox RF22R7351SR",
    price: 7999.9,
    installments: "12x sem juros de R$ 666,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Samsung",
  },
  {
    id: 74,
    name: "Refrigerador LG InstaView 601L Inox GC-X247CSAV",
    price: 6999.9,
    installments: "12x sem juros de R$ 583,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "LG",
  },
  {
    id: 75,
    name: "Geladeira Consul Frost Free 386L Branca CRM43NB",
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Consul",
  },
  {
    id: 76,
    name: "Refrigerador Brastemp Evox 503L Inox BRE62AE",
    price: 3799.9,
    installments: "12x sem juros de R$ 316,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Brastemp",
  },
  {
    id: 77,
    name: "Geladeira Electrolux French Door 540L Branca DM83X",
    price: 4799.9,
    installments: "12x sem juros de R$ 399,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Geladeiras",
    brand: "Electrolux",
  },

  // TVs - 25 produtos
  {
    id: 23,
    name: 'Smart TV Samsung 55" 4K Crystal UHD UN55AU7700',
    price: 2299.9,
    installments: "12x sem juros de R$ 191,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Samsung",
  },
  {
    id: 24,
    name: 'Smart TV LG 50" 4K NanoCell 50NANO75SPA',
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "LG",
  },
  {
    id: 78,
    name: 'Smart TV Sony 65" 4K OLED Bravia XR-65A80L',
    price: 5999.9,
    installments: "12x sem juros de R$ 499,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Sony",
  },
  {
    id: 79,
    name: 'Smart TV Samsung 75" 4K QLED QN75Q60C',
    price: 4999.9,
    installments: "12x sem juros de R$ 416,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Samsung",
  },
  {
    id: 80,
    name: 'Smart TV LG 65" 4K OLED OLED65C3PSA',
    price: 6999.9,
    installments: "12x sem juros de R$ 583,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "LG",
  },
  {
    id: 81,
    name: 'Smart TV TCL 43" 4K UHD 43P635',
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "TCL",
  },
  {
    id: 82,
    name: 'Smart TV Philips 55" 4K UHD 55PUG7408/78',
    price: 2199.9,
    installments: "12x sem juros de R$ 183,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Philips",
  },
  {
    id: 83,
    name: 'Smart TV Hisense 50" 4K UHD 50A6G',
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Hisense",
  },
  {
    id: 84,
    name: 'Smart TV Samsung 32" Full HD UN32T4300AG',
    price: 999.9,
    installments: "12x sem juros de R$ 83,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Samsung",
  },
  {
    id: 85,
    name: 'Smart TV LG 43" 4K UHD 43UP7500PSF',
    price: 1699.9,
    installments: "12x sem juros de R$ 141,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "LG",
  },
  {
    id: 86,
    name: 'Smart TV Sony 55" 4K LED KD-55X75WL',
    price: 2999.9,
    installments: "12x sem juros de R$ 249,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Sony",
  },
  {
    id: 87,
    name: 'Smart TV TCL 65" 4K QLED 65C735',
    price: 3799.9,
    installments: "12x sem juros de R$ 316,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "TCL",
  },
  {
    id: 88,
    name: 'Smart TV Philips 65" 4K OLED 65OLED708/78',
    price: 5499.9,
    installments: "12x sem juros de R$ 458,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Philips",
  },
  {
    id: 89,
    name: 'Smart TV Hisense 75" 4K UHD 75A6G',
    price: 3299.9,
    installments: "12x sem juros de R$ 274,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Hisense",
  },
  {
    id: 90,
    name: 'Smart TV Samsung 85" 4K Crystal UHD UN85AU8000',
    price: 7999.9,
    installments: "12x sem juros de R$ 666,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Samsung",
  },
  {
    id: 91,
    name: 'Smart TV LG 77" 4K OLED OLED77G3PSA',
    price: 12999.9,
    installments: "12x sem juros de R$ 1.083,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "LG",
  },
  {
    id: 92,
    name: 'Smart TV Sony 50" 4K Google TV KD-50X75WL',
    price: 2599.9,
    installments: "12x sem juros de R$ 216,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Sony",
  },
  {
    id: 93,
    name: 'Smart TV TCL 55" 4K Mini LED 55C845',
    price: 4299.9,
    installments: "12x sem juros de R$ 358,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "TCL",
  },
  {
    id: 94,
    name: 'Smart TV Philips 50" 4K Ambilight 50PUG7408/78',
    price: 2399.9,
    installments: "12x sem juros de R$ 199,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Philips",
  },
  {
    id: 95,
    name: 'Smart TV Hisense 55" 4K ULED 55U7H',
    price: 2799.9,
    installments: "12x sem juros de R$ 233,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Hisense",
  },
  {
    id: 96,
    name: 'Smart TV Samsung 40" Full HD UN40T5300AG',
    price: 1299.9,
    installments: "12x sem juros de R$ 108,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Samsung",
  },
  {
    id: 97,
    name: 'Smart TV LG 55" 4K NanoCell 55NANO76SQA',
    price: 2699.9,
    installments: "12x sem juros de R$ 224,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "LG",
  },
  {
    id: 98,
    name: 'Smart TV Sony 43" 4K Google TV KD-43X75WL',
    price: 2199.9,
    installments: "12x sem juros de R$ 183,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Sony",
  },
  {
    id: 99,
    name: 'Smart TV TCL 50" 4K UHD 50P635',
    price: 1899.9,
    installments: "12x sem juros de R$ 158,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "TCL",
  },
  {
    id: 100,
    name: 'Smart TV Philips 43" 4K UHD 43PUG7408/78',
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    brand: "Philips",
  },

  // FOGÕES - 25 produtos
  {
    id: 4,
    name: "Fogão Atlas 5 Bocas Mônaco com Forno Grande",
    price: 699.9,
    installments: "12x sem juros de R$ 58,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Atlas",
  },
  {
    id: 5,
    name: "Fogão Brastemp 4 Bocas Clean com Timer BFS4GCR",
    price: 899.9,
    installments: "12x sem juros de R$ 74,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Brastemp",
  },
  {
    id: 101,
    name: "Fogão Electrolux 5 Bocas Tripla Chama 76EXR",
    price: 1199.9,
    installments: "12x sem juros de R$ 99,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Electrolux",
  },
  {
    id: 102,
    name: "Fogão Consul 4 Bocas Facilite CFO4VAR",
    price: 599.9,
    installments: "12x sem juros de R$ 49,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Consul",
  },
  {
    id: 103,
    name: "Fogão Atlas 6 Bocas Agata Glass com Forno",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Atlas",
  },
  {
    id: 104,
    name: "Fogão Brastemp 5 Bocas Ative! BFS5NCR",
    price: 1099.9,
    installments: "12x sem juros de R$ 91,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Brastemp",
  },
  {
    id: 105,
    name: "Fogão Electrolux 4 Bocas Automático 52LXA",
    price: 799.9,
    installments: "12x sem juros de R$ 66,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Electrolux",
  },
  {
    id: 106,
    name: "Fogão Consul 5 Bocas Mesa de Vidro CFO5VAN",
    price: 999.9,
    installments: "12x sem juros de R$ 83,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Consul",
  },
  {
    id: 107,
    name: "Fogão Atlas 4 Bocas Tropical Grill",
    price: 549.9,
    installments: "12x sem juros de R$ 45,82",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Atlas",
  },
  {
    id: 108,
    name: "Fogão Brastemp 6 Bocas Gourmand BFS6GCR",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Brastemp",
  },
  {
    id: 109,
    name: "Fogão Electrolux 5 Bocas Blue Touch 76TXE",
    price: 1299.9,
    installments: "12x sem juros de R$ 108,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Electrolux",
  },
  {
    id: 110,
    name: "Fogão Consul 4 Bocas Erva Doce CFO4NAR",
    price: 649.9,
    installments: "12x sem juros de R$ 54,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Consul",
  },
  {
    id: 111,
    name: "Fogão Atlas 5 Bocas Utile Glass",
    price: 899.9,
    installments: "12x sem juros de R$ 74,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Atlas",
  },
  {
    id: 112,
    name: "Fogão Brastemp 4 Bocas Ative! BFS4TAR",
    price: 749.9,
    installments: "12x sem juros de R$ 62,49",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Brastemp",
  },
  {
    id: 113,
    name: "Fogão Electrolux 6 Bocas Celebrate 76GSV",
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Electrolux",
  },
  {
    id: 114,
    name: "Fogão Consul 5 Bocas Bem Estar CFO5VAB",
    price: 1149.9,
    installments: "12x sem juros de R$ 95,82",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Consul",
  },
  {
    id: 115,
    name: "Fogão Atlas 4 Bocas Mônaco Top Glass",
    price: 799.9,
    installments: "12x sem juros de R$ 66,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Atlas",
  },
  {
    id: 116,
    name: "Fogão Brastemp 5 Bocas Clean BFS5GCR",
    price: 1249.9,
    installments: "12x sem juros de R$ 104,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Brastemp",
  },
  {
    id: 117,
    name: "Fogão Electrolux 4 Bocas Prata 52SBX",
    price: 699.9,
    installments: "12x sem juros de R$ 58,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Electrolux",
  },
  {
    id: 118,
    name: "Fogão Consul 6 Bocas Mesa de Vidro CFO6VAR",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Consul",
  },
  {
    id: 119,
    name: "Fogão Atlas 5 Bocas Agata Top",
    price: 949.9,
    installments: "12x sem juros de R$ 79,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Atlas",
  },
  {
    id: 120,
    name: "Fogão Brastemp 4 Bocas Gourmand BFS4GBR",
    price: 999.9,
    installments: "12x sem juros de R$ 83,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Brastemp",
  },
  {
    id: 121,
    name: "Fogão Electrolux 5 Bocas Inox 76EIX",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Electrolux",
  },
  {
    id: 122,
    name: "Fogão Consul 4 Bocas Facilite Inox CFO4VIX",
    price: 749.9,
    installments: "12x sem juros de R$ 62,49",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Consul",
  },
  {
    id: 123,
    name: "Fogão Atlas 6 Bocas Tropical Glass",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fogões",
    brand: "Atlas",
  },

  // LAVADORAS - 25 produtos
  {
    id: 8,
    name: "Máquina de Lavar Electrolux 12kg Turbo Economia LAC12",
    price: 1299.9,
    installments: "12x sem juros de R$ 108,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Electrolux",
  },
  {
    id: 9,
    name: "Lavadora Brastemp 11kg com Ciclo Edredom BWL11A",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Brastemp",
  },
  {
    id: 124,
    name: "Máquina de Lavar Samsung 11kg Ecobubble WA11M5120SW",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Samsung",
  },
  {
    id: 125,
    name: "Lavadora LG 13kg TurboWash T1316EFHB",
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "LG",
  },
  {
    id: 126,
    name: "Máquina de Lavar Consul 10kg Facilite CWL10AB",
    price: 999.9,
    installments: "12x sem juros de R$ 83,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Consul",
  },
  {
    id: 127,
    name: "Lavadora Electrolux 15kg Turbo Capacidade LAP15",
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Electrolux",
  },
  {
    id: 128,
    name: "Máquina de Lavar Brastemp 9kg Ative! BWL09A",
    price: 1199.9,
    installments: "12x sem juros de R$ 99,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Brastemp",
  },
  {
    id: 129,
    name: "Lavadora Samsung 8.5kg Digital Inverter WA85M4400HS",
    price: 1099.9,
    installments: "12x sem juros de R$ 91,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Samsung",
  },
  {
    id: 130,
    name: "Máquina de Lavar LG 11kg Smart Inverter T2111VS2W",
    price: 1499.9,
    installments: "12x sem juros de R$ 124,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "LG",
  },
  {
    id: 131,
    name: "Lavadora Consul 12kg Bem Estar CWL12AB",
    price: 1299.9,
    installments: "12x sem juros de R$ 108,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Consul",
  },
  {
    id: 132,
    name: "Máquina de Lavar Electrolux 8kg Essencial LES08",
    price: 899.9,
    installments: "12x sem juros de R$ 74,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Electrolux",
  },
  {
    id: 133,
    name: "Lavadora Brastemp 12kg Clean BWL12A",
    price: 1699.9,
    installments: "12x sem juros de R$ 141,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Brastemp",
  },
  {
    id: 134,
    name: "Máquina de Lavar Samsung 16kg AddWash WA16M6360EW",
    price: 2299.9,
    installments: "12x sem juros de R$ 191,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Samsung",
  },
  {
    id: 135,
    name: "Lavadora LG 17kg TurboWash3D T1717EFHB",
    price: 2599.9,
    installments: "12x sem juros de R$ 216,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "LG",
  },
  {
    id: 136,
    name: "Máquina de Lavar Consul 8kg Facilite CWL08AB",
    price: 799.9,
    installments: "12x sem juros de R$ 66,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Consul",
  },
  {
    id: 137,
    name: "Lavadora Electrolux 10kg Premium Care LPR10",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Electrolux",
  },
  {
    id: 138,
    name: "Máquina de Lavar Brastemp 15kg BWL15A",
    price: 2199.9,
    installments: "12x sem juros de R$ 183,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Brastemp",
  },
  {
    id: 139,
    name: "Lavadora Samsung 12kg Ecobubble WA12M5120SW",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Samsung",
  },
  {
    id: 140,
    name: "Máquina de Lavar LG 14kg Smart Inverter T1412EFHB",
    price: 1899.9,
    installments: "12x sem juros de R$ 158,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "LG",
  },
  {
    id: 141,
    name: "Lavadora Consul 16kg CWL16AB",
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Consul",
  },
  {
    id: 142,
    name: "Máquina de Lavar Electrolux 13kg Turbo Economia LAC13",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Electrolux",
  },
  {
    id: 143,
    name: "Lavadora Brastemp 10kg Ative! BWL10A",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Brastemp",
  },
  {
    id: 144,
    name: "Máquina de Lavar Samsung 9kg WA90M4400HS",
    price: 1199.9,
    installments: "12x sem juros de R$ 99,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Samsung",
  },
  {
    id: 145,
    name: "Lavadora LG 12kg TurboWash T1212EFHB",
    price: 1699.9,
    installments: "12x sem juros de R$ 141,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "LG",
  },
  {
    id: 146,
    name: "Máquina de Lavar Consul 14kg CWL14AB",
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Lavadoras",
    brand: "Consul",
  },

  // MICRO-ONDAS - 25 produtos
  {
    id: 6,
    name: "Micro-ondas Panasonic 32L com Grill Inox NN-GT68HSRU",
    price: 459.9,
    installments: "12x sem juros de R$ 38,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Panasonic",
  },
  {
    id: 7,
    name: "Micro-ondas Electrolux 20L Branco MEO21",
    price: 299.9,
    installments: "12x sem juros de R$ 24,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Electrolux",
  },
  {
    id: 147,
    name: "Micro-ondas Brastemp 30L Inox BMS30AR",
    price: 599.9,
    installments: "12x sem juros de R$ 49,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Brastemp",
  },
  {
    id: 148,
    name: "Micro-ondas Samsung 23L MS23F301TAK",
    price: 399.9,
    installments: "12x sem juros de R$ 33,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Samsung",
  },
  {
    id: 149,
    name: "Micro-ondas LG 30L com Grill MS3059L",
    price: 549.9,
    installments: "12x sem juros de R$ 45,82",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "LG",
  },
  {
    id: 150,
    name: "Micro-ondas Consul 20L Branco CMA20AB",
    price: 279.9,
    installments: "12x sem juros de R$ 23,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Consul",
  },
  {
    id: 151,
    name: "Micro-ondas Panasonic 25L Inox NN-ST35HWRU",
    price: 429.9,
    installments: "12x sem juros de R$ 35,82",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Panasonic",
  },
  {
    id: 152,
    name: "Micro-ondas Electrolux 31L com Grill MEG41",
    price: 649.9,
    installments: "12x sem juros de R$ 54,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Electrolux",
  },
  {
    id: 153,
    name: "Micro-ondas Brastemp 32L Gourmand BMG32AR",
    price: 799.9,
    installments: "12x sem juros de R$ 66,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Brastemp",
  },
  {
    id: 154,
    name: "Micro-ondas Samsung 28L MS28J5255UB",
    price: 499.9,
    installments: "12x sem juros de R$ 41,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Samsung",
  },
  {
    id: 155,
    name: "Micro-ondas LG 25L Solo MS2555RA",
    price: 349.9,
    installments: "12x sem juros de R$ 29,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "LG",
  },
  {
    id: 156,
    name: "Micro-ondas Consul 32L Inox CMS32AR",
    price: 579.9,
    installments: "12x sem juros de R$ 48,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Consul",
  },
  {
    id: 157,
    name: "Micro-ondas Panasonic 21L Branco NN-ST25JWRU",
    price: 329.9,
    installments: "12x sem juros de R$ 27,49",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Panasonic",
  },
  {
    id: 158,
    name: "Micro-ondas Electrolux 25L MEO25",
    price: 399.9,
    installments: "12x sem juros de R$ 33,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Electrolux",
  },
  {
    id: 159,
    name: "Micro-ondas Brastemp 20L Ative! BMS20AR",
    price: 449.9,
    installments: "12x sem juros de R$ 37,49",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Brastemp",
  },
  {
    id: 160,
    name: "Micro-ondas Samsung 30L com Grill MS32F303EAK",
    price: 599.9,
    installments: "12x sem juros de R$ 49,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Samsung",
  },
  {
    id: 161,
    name: "Micro-ondas LG 30L EasyClean MS3097AR",
    price: 529.9,
    installments: "12x sem juros de R$ 44,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "LG",
  },
  {
    id: 162,
    name: "Micro-ondas Consul 25L CMA25AB",
    price: 379.9,
    installments: "12x sem juros de R$ 31,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Consul",
  },
  {
    id: 163,
    name: "Micro-ondas Panasonic 27L com Grill NN-GT27JBRU",
    price: 499.9,
    installments: "12x sem juros de R$ 41,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Panasonic",
  },
  {
    id: 164,
    name: "Micro-ondas Electrolux 28L MEO28",
    price: 479.9,
    installments: "12x sem juros de R$ 39,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Electrolux",
  },
  {
    id: 165,
    name: "Micro-ondas Brastemp 25L Clean BMS25AR",
    price: 519.9,
    installments: "12x sem juros de R$ 43,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Brastemp",
  },
  {
    id: 166,
    name: "Micro-ondas Samsung 20L MS20A3010AL",
    price: 319.9,
    installments: "12x sem juros de R$ 26,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Samsung",
  },
  {
    id: 167,
    name: "Micro-ondas LG 20L MS2042L",
    price: 299.9,
    installments: "12x sem juros de R$ 24,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "LG",
  },
  {
    id: 168,
    name: "Micro-ondas Consul 30L Facilite CMS30AB",
    price: 459.9,
    installments: "12x sem juros de R$ 38,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Consul",
  },
  {
    id: 169,
    name: "Micro-ondas Panasonic 34L NN-ST35KWRU",
    price: 649.9,
    installments: "12x sem juros de R$ 54,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Micro-ondas",
    brand: "Panasonic",
  },

  // AIR FRYERS - 25 produtos
  {
    id: 15,
    name: "Air Fryer Mondial 4L Digital Preta AF-30",
    price: 299.9,
    installments: "12x sem juros de R$ 24,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Mondial",
  },
  {
    id: 16,
    name: "Air Fryer Philco 12L Forno Digital PH12L",
    price: 839.9,
    installments: "12x sem juros de R$ 69,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Philco",
  },
  {
    id: 170,
    name: "Air Fryer Electrolux 5.5L Digital EAF55",
    price: 449.9,
    installments: "12x sem juros de R$ 37,49",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Electrolux",
  },
  {
    id: 171,
    name: "Air Fryer Britânia 3.2L BFR32PI",
    price: 199.9,
    installments: "12x sem juros de R$ 16,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Britânia",
  },
  {
    id: 172,
    name: "Air Fryer Cadence 2.3L Perfect Fryer Colors",
    price: 179.9,
    installments: "12x sem juros de R$ 14,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Cadence",
  },
  {
    id: 173,
    name: "Air Fryer Arno 4.1L Super CFRY",
    price: 349.9,
    installments: "12x sem juros de R$ 29,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Arno",
  },
  {
    id: 174,
    name: "Air Fryer Philips Walita 4.1L Viva Collection",
    price: 599.9,
    installments: "12x sem juros de R$ 49,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Philips Walita",
  },
  {
    id: 175,
    name: "Air Fryer Mondial 7L Family AF-07",
    price: 399.9,
    installments: "12x sem juros de R$ 33,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Mondial",
  },
  {
    id: 176,
    name: "Air Fryer Philco 10L Gourmet Red PH10L",
    price: 699.9,
    installments: "12x sem juros de R$ 58,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Philco",
  },
  {
    id: 177,
    name: "Air Fryer Electrolux 3.2L EAF32",
    price: 329.9,
    installments: "12x sem juros de R$ 27,49",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Electrolux",
  },
  {
    id: 178,
    name: "Air Fryer Britânia 5.5L BFR55P",
    price: 279.9,
    installments: "12x sem juros de R$ 23,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Britânia",
  },
  {
    id: 179,
    name: "Air Fryer Cadence 4L Perfect Fryer FRT541",
    price: 249.9,
    installments: "12x sem juros de R$ 20,82",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Cadence",
  },
  {
    id: 180,
    name: "Air Fryer Arno 2.4L Compact CFRY24",
    price: 229.9,
    installments: "12x sem juros de R$ 19,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Arno",
  },
  {
    id: 181,
    name: "Air Fryer Philips Walita 6.2L Essential XL",
    price: 799.9,
    installments: "12x sem juros de R$ 66,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Philips Walita",
  },
  {
    id: 182,
    name: "Air Fryer Mondial 3.5L New Pratic AF-31",
    price: 219.9,
    installments: "12x sem juros de R$ 18,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Mondial",
  },
  {
    id: 183,
    name: "Air Fryer Philco 8L Grill PH8L",
    price: 549.9,
    installments: "12x sem juros de R$ 45,82",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Philco",
  },
  {
    id: 184,
    name: "Air Fryer Electrolux 4.2L Digital EAF42",
    price: 399.9,
    installments: "12x sem juros de R$ 33,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Electrolux",
  },
  {
    id: 185,
    name: "Air Fryer Britânia 2.4L BFR24P",
    price: 159.9,
    installments: "12x sem juros de R$ 13,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Britânia",
  },
  {
    id: 186,
    name: "Air Fryer Cadence 5.5L Perfect Fryer FRT551",
    price: 319.9,
    installments: "12x sem juros de R$ 26,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Cadence",
  },
  {
    id: 187,
    name: "Air Fryer Arno 5.2L Super CFRY52",
    price: 429.9,
    installments: "12x sem juros de R$ 35,82",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Arno",
  },
  {
    id: 188,
    name: "Air Fryer Philips Walita 1.4L Viva Collection Mini",
    price: 399.9,
    installments: "12x sem juros de R$ 33,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Philips Walita",
  },
  {
    id: 189,
    name: "Air Fryer Mondial 6L Premium AF-06",
    price: 359.9,
    installments: "12x sem juros de R$ 29,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Mondial",
  },
  {
    id: 190,
    name: "Air Fryer Philco 15L Jumbo PH15L",
    price: 999.9,
    installments: "12x sem juros de R$ 83,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Philco",
  },
  {
    id: 191,
    name: "Air Fryer Electrolux 7L EAF70",
    price: 529.9,
    installments: "12x sem juros de R$ 44,16",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Electrolux",
  },
  {
    id: 192,
    name: "Air Fryer Britânia 4.5L Digital BFR45D",
    price: 299.9,
    installments: "12x sem juros de R$ 24,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Air Fryers",
    brand: "Britânia",
  },

  // AR CONDICIONADO - 25 produtos
  {
    id: 22,
    name: "Ar Condicionado Split Midea 12000 BTUs Frio 42MAQA12S5",
    price: 1299.9,
    installments: "12x sem juros de R$ 108,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Midea",
  },
  {
    id: 193,
    name: "Ar Condicionado Samsung 9000 BTUs Inverter AR09TVHZDWKNAZ",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Samsung",
  },
  {
    id: 194,
    name: "Ar Condicionado LG 18000 BTUs Dual Inverter S4-Q18K231D",
    price: 2299.9,
    installments: "12x sem juros de R$ 191,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "LG",
  },
  {
    id: 195,
    name: "Ar Condicionado Electrolux 22000 BTUs Frio/Quente TI22F/TI22R",
    price: 2799.9,
    installments: "12x sem juros de R$ 233,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Electrolux",
  },
  {
    id: 196,
    name: "Ar Condicionado Consul 7500 BTUs CBV07BB",
    price: 999.9,
    installments: "12x sem juros de R$ 83,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Consul",
  },
  {
    id: 197,
    name: "Ar Condicionado Midea 18000 BTUs Inverter 42MAQA18S5",
    price: 1899.9,
    installments: "12x sem juros de R$ 158,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Midea",
  },
  {
    id: 198,
    name: "Ar Condicionado Samsung 24000 BTUs Wind Free AR24AVHZDWKNAZ",
    price: 3299.9,
    installments: "12x sem juros de R$ 274,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Samsung",
  },
  {
    id: 199,
    name: "Ar Condicionado LG 12000 BTUs Dual Inverter S4-Q12JA3WF",
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "LG",
  },
  {
    id: 200,
    name: "Ar Condicionado Electrolux 9000 BTUs Ecoturbo VI09F/VI09R",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Electrolux",
  },
  {
    id: 201,
    name: "Ar Condicionado Consul 12000 BTUs CBV12BB",
    price: 1499.9,
    installments: "12x sem juros de R$ 124,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Consul",
  },
  {
    id: 202,
    name: "Ar Condicionado Midea 30000 BTUs 42MAQA30S5",
    price: 2999.9,
    installments: "12x sem juros de R$ 249,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Midea",
  },
  {
    id: 203,
    name: "Ar Condicionado Samsung 18000 BTUs Digital Inverter AR18AVHZDWKNAZ",
    price: 2599.9,
    installments: "12x sem juros de R$ 216,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Samsung",
  },
  {
    id: 204,
    name: "Ar Condicionado LG 9000 BTUs DUAL Inverter S4-Q09WA51A",
    price: 1599.9,
    installments: "12x sem juros de R$ 133,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "LG",
  },
  {
    id: 205,
    name: "Ar Condicionado Electrolux 18000 BTUs Ecoturbo VI18F/VI18R",
    price: 2199.9,
    installments: "12x sem juros de R$ 183,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Electrolux",
  },
  {
    id: 206,
    name: "Ar Condicionado Consul 18000 BTUs CBV18BB",
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Consul",
  },
  {
    id: 207,
    name: "Ar Condicionado Midea 24000 BTUs Inverter 42MAQA24S5",
    price: 2499.9,
    installments: "12x sem juros de R$ 208,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Midea",
  },
  {
    id: 208,
    name: "Ar Condicionado Samsung 12000 BTUs Wind Free AR12BVHZDWKNAZ",
    price: 2199.9,
    installments: "12x sem juros de R$ 183,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Samsung",
  },
  {
    id: 209,
    name: "Ar Condicionado LG 24000 BTUs Dual Inverter S4-Q24K231D",
    price: 2899.9,
    installments: "12x sem juros de R$ 241,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "LG",
  },
  {
    id: 210,
    name: "Ar Condicionado Electrolux 12000 BTUs Ecoturbo VI12F/VI12R",
    price: 1699.9,
    installments: "12x sem juros de R$ 141,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Electrolux",
  },
  {
    id: 211,
    name: "Ar Condicionado Consul 9000 BTUs CBV09BB",
    price: 1199.9,
    installments: "12x sem juros de R$ 99,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Consul",
  },
  {
    id: 212,
    name: "Ar Condicionado Midea 36000 BTUs 42MAQA36S5",
    price: 3599.9,
    installments: "12x sem juros de R$ 299,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Midea",
  },
  {
    id: 213,
    name: "Ar Condicionado Samsung 30000 BTUs AR30AVHZDWKNAZ",
    price: 3999.9,
    installments: "12x sem juros de R$ 333,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Samsung",
  },
  {
    id: 214,
    name: "Ar Condicionado LG 30000 BTUs Dual Inverter S4-W30K23WA",
    price: 3799.9,
    installments: "12x sem juros de R$ 316,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "LG",
  },
  {
    id: 215,
    name: "Ar Condicionado Electrolux 24000 BTUs Ecoturbo VI24F/VI24R",
    price: 2999.9,
    installments: "12x sem juros de R$ 249,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Electrolux",
  },
  {
    id: 216,
    name: "Ar Condicionado Consul 24000 BTUs CBV24BB",
    price: 2699.9,
    installments: "12x sem juros de R$ 224,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Ar Condicionado",
    brand: "Consul",
  },

  // NOTEBOOKS - 25 produtos
  {
    id: 25,
    name: "Notebook Lenovo IdeaPad 3i Intel Core i5 8GB 256GB SSD",
    price: 2599.9,
    installments: "12x sem juros de R$ 216,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Lenovo",
  },
  {
    id: 217,
    name: "Notebook Dell Inspiron 15 3000 Intel Core i3 4GB 1TB",
    price: 1999.9,
    installments: "12x sem juros de R$ 166,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Dell",
  },
  {
    id: 218,
    name: "Notebook HP 246 G8 Intel Core i5 8GB 256GB SSD",
    price: 2399.9,
    installments: "12x sem juros de R$ 199,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "HP",
  },
  {
    id: 219,
    name: "Notebook Acer Aspire 5 AMD Ryzen 5 8GB 512GB SSD",
    price: 2799.9,
    installments: "12x sem juros de R$ 233,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Acer",
  },
  {
    id: 220,
    name: "Notebook ASUS VivoBook 15 Intel Core i7 8GB 512GB SSD",
    price: 3299.9,
    installments: "12x sem juros de R$ 274,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "ASUS",
  },
  {
    id: 221,
    name: "MacBook Air M2 256GB Meia-noite",
    price: 8999.9,
    installments: "12x sem juros de R$ 749,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Apple",
  },
  {
    id: 222,
    name: "Notebook Samsung Book Intel Core i5 8GB 256GB SSD",
    price: 2699.9,
    installments: "12x sem juros de R$ 224,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Samsung",
  },
  {
    id: 223,
    name: "Notebook Lenovo ThinkPad E14 Intel Core i7 16GB 512GB SSD",
    price: 4999.9,
    installments: "12x sem juros de R$ 416,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Lenovo",
  },
  {
    id: 224,
    name: "Notebook Dell Vostro 3510 Intel Core i5 8GB 256GB SSD",
    price: 2899.9,
    installments: "12x sem juros de R$ 241,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Dell",
  },
  {
    id: 225,
    name: "Notebook HP Pavilion Gaming AMD Ryzen 7 16GB 512GB SSD GTX 1650",
    price: 4299.9,
    installments: "12x sem juros de R$ 358,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "HP",
  },
  {
    id: 226,
    name: "Notebook Acer Nitro 5 Intel Core i5 8GB 512GB SSD GTX 1650",
    price: 3799.9,
    installments: "12x sem juros de R$ 316,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Acer",
  },
  {
    id: 227,
    name: "Notebook ASUS TUF Gaming Intel Core i7 16GB 512GB SSD RTX 3050",
    price: 4999.9,
    installments: "12x sem juros de R$ 416,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "ASUS",
  },
  {
    id: 228,
    name: "MacBook Pro M2 512GB Prata",
    price: 12999.9,
    installments: "12x sem juros de R$ 1.083,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Apple",
  },
  {
    id: 229,
    name: "Notebook Samsung Galaxy Book2 Intel Core i7 16GB 512GB SSD",
    price: 4599.9,
    installments: "12x sem juros de R$ 383,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Samsung",
  },
  {
    id: 230,
    name: "Notebook Lenovo Legion 5 AMD Ryzen 7 16GB 512GB SSD RTX 3060",
    price: 5999.9,
    installments: "12x sem juros de R$ 499,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Lenovo",
  },
  {
    id: 231,
    name: "Notebook Dell XPS 13 Intel Core i7 16GB 512GB SSD",
    price: 6999.9,
    installments: "12x sem juros de R$ 583,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Dell",
  },
  {
    id: 232,
    name: "Notebook HP EliteBook 840 Intel Core i5 8GB 256GB SSD",
    price: 3999.9,
    installments: "12x sem juros de R$ 333,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "HP",
  },
  {
    id: 233,
    name: "Notebook Acer Swift 3 AMD Ryzen 5 8GB 256GB SSD",
    price: 2999.9,
    installments: "12x sem juros de R$ 249,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Acer",
  },
  {
    id: 234,
    name: "Notebook ASUS ZenBook 14 Intel Core i5 8GB 512GB SSD",
    price: 3599.9,
    installments: "12x sem juros de R$ 299,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "ASUS",
  },
  {
    id: 235,
    name: "MacBook Air M1 256GB Dourado",
    price: 6999.9,
    installments: "12x sem juros de R$ 583,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Apple",
  },
  {
    id: 236,
    name: "Notebook Samsung Book Intel Core i3 4GB 1TB",
    price: 1799.9,
    installments: "12x sem juros de R$ 149,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Samsung",
  },
  {
    id: 237,
    name: "Notebook Lenovo IdeaPad Gaming 3i Intel Core i5 8GB 256GB SSD GTX 1650",
    price: 3499.9,
    installments: "12x sem juros de R$ 291,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Lenovo",
  },
  {
    id: 238,
    name: "Notebook Dell Latitude 3420 Intel Core i5 8GB 256GB SSD",
    price: 3299.9,
    installments: "12x sem juros de R$ 274,99",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Dell",
  },
  {
    id: 239,
    name: "Notebook HP 14 Intel Celeron 4GB 128GB SSD",
    price: 1399.9,
    installments: "12x sem juros de R$ 116,66",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "HP",
  },
  {
    id: 240,
    name: "Notebook Acer Chromebook Spin 713 Intel Core i5 8GB 256GB SSD",
    price: 2799.9,
    installments: "12x sem juros de R$ 233,32",
    image: "/placeholder.svg?height=300&width=300",
    category: "Notebooks",
    brand: "Acer",
  },
]

interface ProductGridProps {
  searchQuery?: string
}

export function ProductGrid({ searchQuery = "" }: ProductGridProps) {
  const [favorites, setFavorites] = useState<number[]>([])
  const [filteredProducts, setFilteredProducts] = useState(products)
  const { addToCart } = useCart()

  useEffect(() => {
    if (searchQuery.trim() === "") {
      setFilteredProducts(products)
    } else {
      const filtered = products.filter(
        (product) =>
          product.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
          product.brand.toLowerCase().includes(searchQuery.toLowerCase()) ||
          product.category.toLowerCase().includes(searchQuery.toLowerCase()),
      )
      setFilteredProducts(filtered)
    }
  }, [searchQuery])

  const toggleFavorite = (productId: number) => {
    setFavorites((prev) => (prev.includes(productId) ? prev.filter((id) => id !== productId) : [...prev, productId]))
  }

  const handleAddToCart = (product: any) => {
    addToCart(product)
    toast({
      title: "✅ Produto adicionado!",
      description: `${product.name} foi adicionado ao seu carrinho.`,
      duration: 3000,
    })
  }

  return (
    <div className="py-12">
      <div className="container mx-auto px-4">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-gray-800 mb-4">
            {searchQuery ? `🔍 Resultados para "${searchQuery}"` : "🔥 PRODUTOS EM DESTAQUE"}
          </h2>
          <p className="text-gray-600">
            {searchQuery
              ? `${filteredProducts.length} produtos encontrados`
              : "Os melhores preços em eletrodomésticos e smartphones você encontra aqui!"}
          </p>
        </div>

        {filteredProducts.length === 0 ? (
          <div className="text-center py-12">
            <div className="text-6xl mb-4">😔</div>
            <h3 className="text-xl font-semibold mb-2">Nenhum produto encontrado</h3>
            <p className="text-gray-600">Tente buscar por outro termo ou navegue pelas categorias</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {filteredProducts.map((product) => (
              <div
                key={product.id}
                className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow"
              >
                <div className="relative">
                  <div className="w-full h-48 bg-gray-100 flex items-center justify-center">
                    <div className="text-6xl">
                      {product.category === "Smartphones"
                        ? "📱"
                        : product.category === "TVs"
                          ? "📺"
                          : product.category === "Geladeiras"
                            ? "🧊"
                            : product.category === "Fogões"
                              ? "🔥"
                              : product.category === "Air Fryers"
                                ? "🍳"
                                : product.category === "Lavadoras"
                                  ? "👕"
                                  : product.category === "Ar Condicionado"
                                    ? "❄️"
                                    : product.category === "Notebooks"
                                      ? "💻"
                                      : product.category === "Micro-ondas"
                                        ? "📡"
                                        : "⚡"}
                    </div>
                  </div>
                  <button
                    onClick={() => toggleFavorite(product.id)}
                    className="absolute top-2 right-2 p-2 bg-white rounded-full shadow-md hover:bg-gray-50"
                  >
                    <Heart
                      className={`h-5 w-5 ${
                        favorites.includes(product.id) ? "text-red-500 fill-current" : "text-gray-400"
                      }`}
                    />
                  </button>
                  <div className="absolute top-2 left-2 bg-blue-500 text-white px-2 py-1 rounded text-xs font-semibold">
                    {product.brand}
                  </div>
                </div>

                <div className="p-4">
                  <h3 className="text-sm font-medium text-gray-800 mb-2 line-clamp-2">{product.name}</h3>

                  <div className="mb-3">
                    <span className="text-2xl font-bold text-green-600">
                      R$ {product.price.toFixed(2).replace(".", ",")}
                    </span>
                    <p className="text-sm text-gray-500 mt-1">Ou {product.installments}</p>
                  </div>

                  <Button
                    onClick={() => handleAddToCart(product)}
                    className="w-full bg-green-600 hover:bg-green-700 text-white font-semibold"
                  >
                    <ShoppingCart className="h-4 w-4 mr-2" />
                    Adicionar ao carrinho
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}

        {!searchQuery && (
          <div className="text-center mt-12">
            <Button variant="outline" className="px-8 py-3 bg-transparent">
              Ver mais produtos
            </Button>
          </div>
        )}
      </div>
    </div>
  )
}
